### ISSUE TITLE
Group permission should be enforced on TRUNCATE statements

### ISSUE THREAD

**Issue by debussyman** [extragoodlabs/jumpwire#36]
When connecting via SSO, group permissions control which queries should be executed. If a group is not allowed to delete particular labels, the expectation is that a TRUNCATE command would be blocked. However, the query succeeds, removing all rows from the table.

JumpWire version: 4.0.0

Configuration
```yaml
groups:
  Engineers:
    permissions:
      - select:pii
      - select:sensitive
      - select:secret
      - update:pii
      - update:sensitive
```

```shell
ryan=> select staff_id, first_name, last_name, username from staff limit 1;
 staff_id | first_name  | last_name |  username
----------+-------------+-----------+-------------
        4 | John        | Lawrence  | John
(1 rows)

ryan=> truncate table staff;
TRUNCATE TABLE
ryan=> select staff_id, first_name, last_name, username from staff limit 1;
 staff_id | first_name | last_name | username
----------+------------+-----------+----------
(0 rows)
```
